### ISSUE TITLE
[secure-hash]: require is not defined

### ISSUE THREAD

**Issue by Berkmann18** [ForbesLindesay/authentication#11]
I'm trying to use `@authentication/secure-hash` and `@authentication/generate-passcode` in a Quasar project with the Registration page's `<script>` section as follows:
```js
import { hash } from '@authentication/secure-hash';
import generatePassCode, { Encoding } from '@authentication/generate-passcode';

export default {
  data() {
    return {
      // ...
    };
  },
  methods: {
    async register() {
      const password = await generatePassCode(40, Encoding.base91);
      const pwHash = await hash(password);
      //...
    },
  },
};
```

the password generate works as `console.log`ging `password` shows it, **however**, simply having `import { hash } from '@authentication/secure-hash';` (even in a boot file) causes the `require is not defined` error:
```
ReferenceError: require is not defined
    at Object.eval (index.js?1146:6)
    at eval (index.js:165)
    at Object../node_modules/node-gyp-build/index.js (vendor.js:4450)
    at __webpack_require__ (app.js:854)
    at fn (app.js:151)
    at Object.eval (index.js?1b94:1)
    at eval (index.js:5)
    at Object../node_modules/sodium-native/index.js (vendor.js:5947)
    at __webpack_require__ (app.js:854)
    at fn (app.js:151)
```

**Comment by ForbesLindesay** [comment]
secure-hash is not designed to work client side. You may be able to build something using [Web Crypto's deriveKey API](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/deriveKey) and [PBKDF2 with at least 100,000 iterations](https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#pbkdf2) I have not tested this and I'm not confident though. I am considering re-writing secure-hash to use Bcrypt or PBKDF2 as they are simpler to tune, but secure-hash currently uses Argon2id.

**Comment by Berkmann18** [comment]
That makes sense. I managed to find an alternative in the meantime, I wonder if I'll need to change that later on.
