### ISSUE TITLE
This vs `cookie-parser`

### ISSUE THREAD

**Issue by Berkmann18** [ForbesLindesay/authentication#27]
I haven't used this package before and the documentation (unlike the one for `@authentication/cookie-session`) don't seem to suggest this should **replace** or be used **alongside** `cookie-parser`. The reason for this question is that I'm trying to see if this will make `cookie-parser` redundant or possibly hinder the security benefits from this package.

And side question, how would you advise using the three cookie endpoints (from https://www.atauthentication.com/docs/cookie.html#usage)?

**Comment by ForbesLindesay** [comment]
You should not need any additional lib (such as cookie-parser) when using `@authentication/cookie`
